### ISSUE TITLE
中文符号排版错误

### ISSUE THREAD

**Issue by iamapig120** [Icemic/huozi.js#2]
![image](https://user-images.githubusercontent.com/16359124/36101037-2e2db520-1043-11e8-9335-286c27c7aab1.png)
开启标点压缩，字体可能是雅黑UI，
，“
符号排版错误

**Comment by Icemic** [comment]
试试 `fixLeftQuote` 参数？

**Comment by iamapig120** [comment]
看了一下似乎是微软雅黑字体更新后重新设计引发的问题，另外我是在这个项目的demo上看到的这个问题……所以不太清楚怎么设置这个参数……
秋季更新后，雅黑的标点被重新设计了
https://www.ithome.com/html/win10/321635.htm
![image](https://user-images.githubusercontent.com/16359124/36139395-49b08382-10d8-11e8-9b5a-f7ba4499d99d.png)

**Comment by Icemic** [comment]
这次更改之后，`fixLeftQuote` 应该是能解决问题的，之前是怎么都不行……
demo 里没有提供修改的方法，可以拉代码下来看。这个参数当初就是为了解决雅黑的问题加上的 = =
