### ISSUE TITLE
英文字母超出一行未强制折行

### ISSUE THREAD

**Issue by xiangpaopao** [Icemic/huozi.js#5]
![image](https://user-images.githubusercontent.com/2008850/54289356-f7df2580-45e3-11e9-98dc-250c707f6072.png)

如图 有个很长的单词，超出一屏的宽度不会自动折行

**Comment by Icemic** [comment]
By design, won't fix. But PRs are always welcome.

活字的设计思路是「将 CJK 文字放在格子中，并将其中混有的少量西文内容较合适地填充在其间的整格数宽度内」，用于「常见的游戏文本」，而非为严格西文排版设计。
西文排版中，将长单词强制折行并非一个正确的解决方式，而正确的方式——字符间距微调及连字符折行算法向来是一个难点，目前我也没有足够的这方面知识去解决。
在常见的游戏文本中，这种情况几乎不会遇到，即便有也很容易通过手工添加空格的方式解决。

以后或许我会考虑使用已有的成熟开源算法，以满足纯西文排版场景。

**Comment by xiangpaopao** [comment]
> By design, won't fix. But PRs are always welcome.
> 
> 活字的设计思路是「将 CJK 文字放在格子中，并将其中混有的少量西文内容较合适地填充在其间的整格数宽度内」，用于「常见的游戏文本」，而非为严格西文排版设计。
> 西文排版中，将长单词强制折行并非一个正确的解决方式，而正确的方式——字符间距微调及连字符折行算法向来是一个难点，目前我也没有足够的这方面知识去解决。
> 在常见的游戏文本中，这种情况几乎不会遇到，即便有也很容易通过手工添加空格的方式解决。
> 
> 以后或许我会考虑使用已有的成熟开源算法，以满足纯西文排版场景。

谢了，一路找canvas里中英文混排的断行算法找到你这
